.open smash.db

DROP TABLE IF EXISTS ctemp;
DROP TABLE IF EXISTS ttemp;
DROP TABLE IF EXISTS ptemp;
DROP TABLE IF EXISTS stemp;
DROP TABLE IF EXISTS ftemp;
DROP TABLE IF EXISTS PTtemp;
DROP TABLE IF EXISTS temptiers;
DROP TABLE IF EXISTS Character;
DROP TABLE IF EXISTS Tournament;
DROP TABLE IF EXISTS Player;
DROP TABLE IF EXISTS SetSingles;
DROP TABLE IF EXISTS FightSingles;
DROP TABLE IF EXISTS PlayerTournament;
DROP TABLE IF EXISTS Tier;
DROP TABLE IF EXISTS Matchup;